-- 코드를 작성해주세요
WITH RECURSIVE RC AS
(
    SELECT ID, 1 AS LEVEL FROM ECOLI_DATA WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID AS ID, RC.LEVEL + 1 AS LEVEL
    FROM ECOLI_DATA E, RC
    WHERE E.PARENT_ID = RC.ID
)
SELECT ID
FROM RC
WHERE LEVEL = 3
ORDER BY ID