-- 코드를 입력하세요
SELECT DISTINCT CC.CAR_ID, CC.CAR_TYPE, CC.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
ON CC.CAR_TYPE = DP.CAR_TYPE
WHERE CC.CAR_TYPE IN ('세단', 'SUV') AND CC.CAR_ID NOT IN (
SELECT RH.CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH WHERE START_DATE <= '2022-11-30' AND END_DATE > '2022-11-01') AND DP.DURATION_TYPE = '30일 이상' AND CC.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE/100) >= 500000 AND CC.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE/100) < 2000000
ORDER BY FEE DESC, CC.CAR_TYPE, CC.CAR_ID DESC