-- 코드를 작성해주세요
WITH RECURSIVE RC AS
(
    SELECT ID, 1 AS GENERATION FROM ECOLI_DATA WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID AS ID, RC.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E, RC
    WHERE E.PARENT_ID = RC.ID
)
SELECT COUNT(*), GENERATION
FROM RC
WHERE NOT EXISTS (
SELECT ID FROM ECOLI_DATA
WHERE ECOLI_DATA.PARENT_ID = RC.ID)
GROUP BY GENERATION
ORDER BY GENERATION