-- 코드를 작성해주세요
SELECT G.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT D
JOIN HR_EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
JOIN (SELECT EMP_NO, SUM(SCORE) SCORE
     FROM HR_GRADE
     GROUP BY EMP_NO) G
ON E.EMP_NO = G.EMP_NO
WHERE G.SCORE = (
    SELECT MAX(TOTAL_SCORE)
    FROM (
        SELECT SUM(SCORE) TOTAL_SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
    ) X
)