-- 코드를 입력하세요
# SELECT * FROM BOOK_SALES
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES BS ON
B.BOOK_ID = BS.BOOK_ID
WHERE MONTH(BS.SALES_DATE) = 1
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY